export const positions = {
  QB: ["Field General", "Improviser", "Scrambler"],
  HB: ["Elusive Back", "Power Back", "Receiving Back"],
  FB: ["Blocking", "Utility"],
  WR: ["Deep Threat", "Physical", "Route Runner"],
  TE: ["Blocking", "Possession", "Vertical Threat"],
  LT: ["Agile", "Pass Protector", "Power"],
  LG: ["Agile", "Pass Protector", "Power"],
  C: ["Agile", "Pass Protector", "Power"],
  RG: ["Agile", "Pass Protector", "Power"],
  RT: ["Agile", "Pass Protector", "Power"],
  LE: ["Power Rusher", "Run Stopper", "Speed Rusher"],
  RE: ["Power Rusher", "Run Stopper", "Speed Rusher"],
  DT: ["Power Rusher", "Run Stopper", "Speed Rusher"],
  LOLB: ["Pass Coverage", "Power Rusher", "Run Stopper", "Speed Rusher"],
  MLB: ["Field General", "Pass Coverage", "Run Stopper"],
  ROLB: ["Pass Coverage", "Power Rusher", "Run Stopper", "Speed Rusher"],
  CB: ["Man to Man", "Slot", "Zone"],
  FS: ["Hybrid", "Run Support", "Zone"],
  SS: ["Hybrid", "Run Support", "Zone"],
  K: ["Accurate", "Power"],
  P: ["Accurate", "Power"],
};
